# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set([('price_category', 'price_product')]),
        ),
    ]
