# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manager.Category'),
            preserve_default=False,
        ),
    ]
