# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20170125_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Item',
            name='qty',
        ),
        migrations.AddField(
            model_name='Item',
            name='enough',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
