# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_product', models.FloatField(default=0.0)),
                ('price_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Category')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='price_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Store'),
        ),
    ]
