# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20170128_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='itens',
            field=models.ManyToManyField(to='manager.Item'),
        ),
    ]
